### ISSUE TITLE
Non-movable objects with resized floor plan

### ISSUE THREAD

**Issue by Mko86** [furnishup/blueprint3d#110]
Dear all, congratulations for the job! You have developed a great project.

Carrying out various tests, I realized that if I resize the map (in some cases) the objects are not movable. 

If this bug is not fixable, into the "Edit floorplan" section, is there any alarm that can be activated to let you know in advance when this problem occurs?

Below a screenshot I resized the demo floorplan to show you this problem. After resized it, try to move the objects into the room.

![3c0c95d8-f7d4-4a7b-9818-d3ba63d2efaa](https://user-images.githubusercontent.com/94693392/143237687-75a1e94a-9b7f-471d-b0cc-e8d5ded054b7.jpg)

Tks in advance and good job

**Comment by Mko86** [comment]
I solved it by correcting the FloorItem.prototype.isValidPosition function into the file blueprint3d.js

**Comment by Mko86** [comment]
Below the procedure to solve this issue:

- Open the file blueprint3d.js
- Check the function FloorItem.prototype.isValidPosition
- Replace the complete function with the below code:

		function inside(point, vs) {
			
			var ck = 0;
			for (var p = 0; p < point.length; p++) {
				var inside = false;
				var x = point[p][0], y = point[p][1];
			
				for (var i = 0, j = vs.length - 1; i < vs.length; j = i++) {
					var xi = vs[i][0], yi = vs[i][1];
					var xj = vs[j][0], yj = vs[j][1];
					
					var intersect = ((yi > y) != (yj > y))
						&& (x < (xj - xi) * (y - yi) / (yj - yi) + xi);
					if (intersect) inside = !inside;
				}
					if (inside == true) {ck++;} 
			}

			if (ck == point.length) {
				return true;
			} else {
				return false;
			}
		  
		};


        FloorItem.prototype.isValidPosition = function (vec3) {
           
            var corners = this.getCorners('x', 'z', vec3);
            var rooms = this.model.floorplan.getRooms();
            var isInARoom = false;

			for (var r = 0; r < rooms.length; r++) {	

				coo_rooms = new Array();
				for (var i = 0; i < rooms[r].corners.length; i++) {
					coo_rooms[i] = new Array();
					coo_rooms[i][0] = rooms[r].corners[i].x;
					coo_rooms[i][1] = rooms[r].corners[i].y;
				}
				
				coo_obj = new Array();
				for (var i = 0; i < corners.length; i++) {
					coo_obj[i] = new Array();
					coo_obj[i][0] = corners[i].x;
					coo_obj[i][1] = corners[i].y;
				}

				if (inside(coo_obj, coo_rooms) == true) {
					isInARoom = true;
				}

			}
			
            if (!isInARoom) {
                return false;
            }

            return true;

        }

**Comment by todverse** [comment]
I found how to solve the problem deeper, when you run the `grunt` command again, the file you are talking about is updated, so if along the path src/items/floor_item.js replace the isValidPosition method with this the problem will be solved globally
```
private inside(point, vs) {
  	
      var ck = 0;
      for (var p = 0; p < point.length; p++) {
        var inside = false;
        var x = point[p][0], y = point[p][1];
      
        for (var i = 0, j = vs.length - 1; i < vs.length; j = i++) {
          var xi = vs[i][0], yi = vs[i][1];
          var xj = vs[j][0], yj = vs[j][1];
          
          var intersect = ((yi > y) != (yj > y))
            && (x < (xj - xi) * (y - yi) / (yj - yi) + xi);
          if (intersect) inside = !inside;
        }
          if (inside == true) {ck++;} 
      }
    
      if (ck == point.length) {
        return true;
      } else {
        return false;
      }
      
    }
    /** */
    public isValidPosition(vec3): boolean {
      var corners = this.getCorners('x', 'z', vec3);
      var rooms = this.model.floorplan.getRooms();
      var isInARoom = false;

  	for (var r = 0; r < rooms.length; r++) {	

  		var coo_rooms = new Array();
  		for (var i = 0; i < rooms[r].corners.length; i++) {
  			coo_rooms[i] = new Array();
  			coo_rooms[i][0] = rooms[r].corners[i].x;
  			coo_rooms[i][1] = rooms[r].corners[i].y;
  		}
  		
  		var coo_obj = new Array();
  		for (var i = 0; i < corners.length; i++) {
  			coo_obj[i] = new Array();
  			coo_obj[i][0] = corners[i].x;
  			coo_obj[i][1] = corners[i].y;
  		}

  		if (this.inside(coo_obj, coo_rooms) == true) {
  			isInARoom = true;
  		}

  	}
  	
      if (!isInARoom) {
          return false;
      }

      return true;
    }
   ```
