### ISSUE TITLE
Is it possible to change the height of the wall?

### ISSUE THREAD

**Issue by nxt-kevin** [furnishup/blueprint3d#12]
When the floorplan is drawn (or loaded from the file), is it possible to change the height of the wall in the design viewer? Maybe via the javascript code? Is there any parameter to set the height of the wall displayed here?
Thank you

**Comment by akoskm** [comment]
See line https://github.com/furnishup/blueprint3d/blob/master/src/model/wall.js#L15

![wall](https://cloud.githubusercontent.com/assets/3111627/16256540/1b71f85c-3853-11e6-850e-1e4b0b9b616c.png)

Is that what you're looking for?

**Comment by nxt-kevin** [comment]
Yes it is. Thank you for your answer.

**Comment by akoskm** [comment]
@nxt-kevin so this can be closed, right?

**Comment by Sivabilla** [comment]
hey @nxt-kevin @akoskm  i just trying the same functionality...any ideas?

i went to this link 
https://github.com/furnishup/blueprint3d/blob/master/src/model/wall.js#L15

but it throws 404
