### ISSUE TITLE
Models are getting blurred when zoomed out.

### ISSUE THREAD

**Issue by tarun29061990** [furnishup/blueprint3d#2]
I have added a low poly model with a 512px texture and its edges are getting blurred? 
<img width="870" alt="screen shot 2015-10-23 at 4 52 14 pm" src="https://cloud.githubusercontent.com/assets/1535607/10691339/ed5cfbfe-79a5-11e5-8840-6807341f006d.png">
Please Help ?

**Comment by tarun29061990** [comment]
Can you please help me in resolving this?

**Comment by akoskm** [comment]
The quality of the rendered model depends on the capabilities of your pc, browser, video card but also on the model itself. This has barely anything to do with blueprint3d itself, you can close this issue.

**Comment by tarun29061990** [comment]
I have already fixed this issue a long back, sorry for not updating the issue. Here I am talking about blurring not quality, blurring happens when the device pixel ratio is not set. So have to add one line in three/main.ts i.e renderer.devicePixelRatio = window.devicePixelRatio
